apiVersion: apps/v1
kind: Deployment
metadata:
  name: employees-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: employees-api
  template:
    metadata:
      labels:
        app: employees-api
    spec:
      containers:
        - name: employees-api
          image: employees_api:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: employees-api-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: employees-api-config
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: employees-db-secret
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: employees-db-secret
                  key: DB_PASS
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: employees-db-secret
                  key: DB_NAME
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: employees-api-config
                  key: API_PORT
